version: '3'

services:
  db:
    container_name: 'advanced-backend-db'
    image: postgres
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres

volumes:
  data:
    driver: local

networks:
  postgres:
    driver: bridge
